driver:
   name: vagrant

provisioner:
  name: chef_solo
  product_name: chef
  enforce_idempotency: true
  multiple_converge: 2
  solo_rb:
    treat_deprecation_warnings_as_errors: true

verifier:
  name: inspec

platforms:
  - name: amazonlinux
    driver_config:
      box: mvbcoding/awslinux
  # - name: centos-6
  - name: centos-7
  - name: debian-8
  - name: debian-9
  - name: fedora-latest
  - name: opensuse-leap
  - name: ubuntu-16.04
  - name: ubuntu-18.04

suites:
  - name: default
    run_list:
    - recipe[test::default]
  # - name: ssl
  #   run_list:
  #   - recipe[test::mod_ssl]

  # - name: prefork
  #   run_list:
  #   - recipe[fqdn]
  #   - recipe[apache2_test::setup]
  #   - recipe[apache2_test::default]
  #   - recipe[apache2_test::broken_conf]
  #   - recipe[apache2_test::modules]
  #   - recipe[apache2_test::mod_cgi]
  # # not supported by apache 2.4 without source compile with non-maintainer patches
  # # - recipe[apache2_test::mod_fastcgi]
  #   - recipe[apache2_test::mod_perl]
  #   - recipe[apache2_test::mod_php]
  # # - recipe[apache2_test::mod_proxy_ajp]
  #   - recipe[apache2_test::mod_python]
  #   - recipe[apache2_test::mod_ssl]
  #   verifier:
  #     inspec_tests:
  #       - test/integration/default
  #   attributes:
  #     machine_fqdn: working.computers.biz
  #     machine_fqdn_as_hostname: true
  #     apache:
  #       mpm: prefork
  #   includes:
  #     - centos-7
  #     - debian-8
  #     - ubuntu-16.04
  #     - ubuntu-18.04
  #
  # - name: worker
  #   run_list:
  #   - recipe[fqdn]
  #   - recipe[apache2_test::setup]
  #   - recipe[apache2_test::default]
  #   - recipe[apache2_test::basic_web_app]
  #   - recipe[apache2_test::broken_conf]
  #   - recipe[apache2_test::modules]
  #   attributes:
  #     machine_fqdn: working.computers.biz
  #     machine_fqdn_as_hostname: true
  #     apache:
  #       mpm: worker
  #   includes:
  #     - centos-7
  #     - ubuntu-16.04
  #
  # - name: event
  #   run_list:
  #   - recipe[fqdn]
  #   - recipe[apache2_test::setup]
  #   - recipe[apache2_test::default]
  #   - recipe[apache2_test::basic_web_app]
  #   - recipe[apache2_test::broken_conf]
  #   - recipe[apache2_test::modules]
  #   attributes:
  #     machine_fqdn: working.computers.biz
  #     machine_fqdn_as_hostname: true
  #     apache:
  #       mpm: event
  #   verifier:
  #     inspec_tests:
  #       - test/integration/default
  #   includes:
  #     - ubuntu-16.04
